### ISSUE TITLE
Echo command

### ISSUE THREAD

**Issue by edooarda** [NataliaMedeiros/minishell#5]
The command echo, when is used without an argument, is giving a seg fault.

**Comment by edooarda** [comment]
echo -n only, need to return a flag.

[minishell]: echo -n
flag 0
struct[1]:
echo 
-n
outfile: None
infile: None
-n

echo only return new line, echo -n, return nothing (flag 1)

**Comment by edooarda** [comment]
Remove space from echo argument on end of struct

**Comment by edooarda** [comment]
This could be in execution, or on the $ or in the echo

Case:
**_echo $?_**   return the exit code (for example 1 or 127)

return of it:

[minishell]: echo $?
hello
flag 0
struct[1]:
echo <-
JS_DEBUG_TOPICS=JS ERROR;JS LOG?<-
outfile: None
infile: None
JS_DEBUG_TOPICS=JS ERROR;JS LOG?

**Comment by NataliaMedeiros** [comment]
Fix command echo $"HOME", it's not returning the right value
